import type { ToolDefinition } from "@/lib/tools/tool-types";

const published = "published" as const;

export const additionalPublishedTools: ToolDefinition[] = [
  {
    slug: "remove-extra-spaces",
    title: "Remove Extra Spaces",
    shortTitle: "Extra Spaces",
    description: "Collapse awkward spacing, normalize tabs, trim lines, and clean punctuation gaps.",
    category: "text",
    status: published,
    seoTitle: "Remove Extra Spaces - Clean Spacing from Text",
    seoDescription:
      "Remove extra spaces from pasted text locally. Collapse repeated spaces, trim lines, normalize tabs, and clean spaces around punctuation.",
    keywords: ["remove extra spaces", "clean spacing", "collapse spaces", "trim text"],
    relatedTools: ["text-cleaner", "remove-empty-lines", "find-and-replace", "word-counter"],
    isLocalOnly: true,
  },
  {
    slug: "remove-empty-lines",
    title: "Remove Empty Lines",
    shortTitle: "Empty Lines",
    description: "Delete blank rows or collapse big gaps while keeping useful paragraph spacing.",
    category: "text",
    status: published,
    seoTitle: "Remove Empty Lines - Delete Blank Lines from Text",
    seoDescription:
      "Remove empty lines from pasted text in your browser. Delete all blank rows, collapse repeated blanks, trim whitespace-only lines, and preserve paragraphs.",
    keywords: ["remove empty lines", "delete blank lines", "collapse empty lines", "clean text lines"],
    relatedTools: ["remove-extra-spaces", "line-counter", "text-cleaner", "sort-lines"],
    isLocalOnly: true,
  },
  {
    slug: "find-and-replace",
    title: "Find and Replace Text",
    shortTitle: "Find Replace",
    description: "Find text, replace it safely, count matches, and handle regular expressions with friendly errors.",
    category: "text",
    status: published,
    seoTitle: "Find and Replace Text - Replace Text Locally",
    seoDescription:
      "Find and replace text locally in your browser with match case, whole word, regex, replace first, and replace all options.",
    keywords: ["find and replace", "replace text", "regex replace", "text replacement"],
    relatedTools: ["text-cleaner", "case-converter", "remove-extra-spaces", "text-diff-checker"],
    isLocalOnly: true,
  },
  {
    slug: "text-diff-checker",
    title: "Text Diff Checker",
    shortTitle: "Text Diff",
    description: "Compare two text blocks with line or word diff summaries and readable change highlighting.",
    category: "text",
    status: published,
    seoTitle: "Text Diff Checker - Compare Two Text Blocks",
    seoDescription:
      "Compare text locally in your browser. Check line differences, word changes, additions, removals, and copy a quick diff summary.",
    keywords: ["text diff checker", "compare text", "find text differences", "line diff"],
    relatedTools: ["find-and-replace", "line-counter", "word-counter", "text-cleaner"],
    isLocalOnly: true,
  },
  {
    slug: "speaking-time-calculator",
    title: "Speaking Time Calculator",
    shortTitle: "Speaking Time",
    description: "Estimate how long a speech, script, video, podcast, or voiceover will take to say aloud.",
    category: "social-writing",
    status: published,
    seoTitle: "Speaking Time Calculator - Estimate Script Duration",
    seoDescription:
      "Calculate speaking time from pasted text with slow, average, fast, and custom words-per-minute settings saved locally.",
    keywords: ["speaking time calculator", "speech time", "script duration", "words per minute"],
    relatedTools: ["reading-time-calculator", "word-counter", "character-counter", "meta-description-checker"],
    isLocalOnly: true,
  },
  {
    slug: "instagram-line-breaks",
    title: "Instagram Line Break Formatter",
    shortTitle: "Instagram Breaks",
    description: "Clean caption spacing, trim hashtags, and preview line breaks before posting.",
    category: "social-writing",
    status: published,
    seoTitle: "Instagram Line Break Formatter - Clean Caption Spacing",
    seoDescription:
      "Format Instagram caption line breaks locally. Trim lines, remove duplicate hashtags, move hashtags to a final block, and copy the cleaned caption.",
    keywords: ["instagram line breaks", "caption formatter", "instagram caption spacing", "hashtag cleanup"],
    relatedTools: ["instagram-character-counter", "linkedin-post-formatter", "whatsapp-text-formatter", "character-counter"],
    isLocalOnly: true,
  },
  {
    slug: "instagram-character-counter",
    title: "Instagram Character Counter",
    shortTitle: "Instagram Counter",
    description: "Check Instagram caption, bio, username, and name-field length with hashtag and mention counts.",
    category: "social-writing",
    status: published,
    seoTitle: "Instagram Character Counter - Caption and Bio Length",
    seoDescription:
      "Count Instagram caption, bio, username, and name field characters locally with remaining characters, hashtags, mentions, and word count.",
    keywords: ["instagram character counter", "instagram caption limit", "instagram bio length", "hashtag counter"],
    relatedTools: ["instagram-line-breaks", "twitter-character-counter", "character-counter", "meta-description-checker"],
    isLocalOnly: true,
  },
  {
    slug: "twitter-character-counter",
    title: "X/Twitter Character Counter",
    shortTitle: "X Counter",
    description: "Estimate X/Twitter post length, remaining characters, URLs, words, and thread chunks.",
    category: "social-writing",
    status: published,
    seoTitle: "X/Twitter Character Counter - Estimate Post Length",
    seoDescription:
      "Count X/Twitter post characters locally with a 280-character default, long-post option, URL count, words, and thread estimate.",
    keywords: ["twitter character counter", "x character counter", "tweet length", "280 characters"],
    relatedTools: ["character-counter", "instagram-character-counter", "linkedin-post-formatter", "word-counter"],
    isLocalOnly: true,
  },
  {
    slug: "linkedin-post-formatter",
    title: "LinkedIn Post Formatter",
    shortTitle: "LinkedIn Formatter",
    description: "Clean post spacing, normalize bullets, preserve paragraphs, and preview a professional text post.",
    category: "social-writing",
    status: published,
    seoTitle: "LinkedIn Post Formatter - Clean Post Text",
    seoDescription:
      "Format LinkedIn-style post text locally. Clean spaces, preserve paragraphs, normalize bullets, trim lines, preview, and copy.",
    keywords: ["linkedin post formatter", "format linkedin post", "linkedin line breaks", "post formatter"],
    relatedTools: ["instagram-line-breaks", "whatsapp-text-formatter", "word-counter", "character-counter"],
    isLocalOnly: true,
  },
  {
    slug: "whatsapp-text-formatter",
    title: "WhatsApp Text Formatter",
    shortTitle: "WhatsApp Text",
    description: "Clean chat text, convert lines to bullets or numbers, and preview the message as a simple bubble.",
    category: "social-writing",
    status: published,
    seoTitle: "WhatsApp Text Formatter - Clean Chat Messages",
    seoDescription:
      "Format chat message text locally. Clean spaces, preserve line breaks, create bullet or numbered lists, add separators, and copy the result.",
    keywords: ["whatsapp text formatter", "chat message formatter", "bullet message", "clean forwarded text"],
    relatedTools: ["linkedin-post-formatter", "instagram-line-breaks", "list-cleaner", "text-cleaner"],
    isLocalOnly: true,
  },
  {
    slug: "meta-description-checker",
    title: "Meta Description Length Checker",
    shortTitle: "Meta Description",
    description: "Check SEO description length, preview a search snippet, and stay near a practical character range.",
    category: "social-writing",
    status: published,
    seoTitle: "Meta Description Length Checker - Preview SEO Snippets",
    seoDescription:
      "Check meta description length locally with 120-160 character guidance, search snippet preview, title and URL fields, and copy.",
    keywords: ["meta description checker", "meta description length", "seo snippet preview", "description counter"],
    relatedTools: ["character-counter", "slug-generator", "word-counter", "twitter-character-counter"],
    isLocalOnly: true,
  },
  {
    slug: "xml-validator",
    title: "XML Validator",
    shortTitle: "XML Validator",
    description: "Validate XML locally, inspect root elements, and get readable parser errors.",
    category: "developer",
    status: published,
    seoTitle: "XML Validator - Validate XML Locally",
    seoDescription:
      "Validate XML in your browser with friendly parse errors, root element name, element count, attribute count, and sample XML.",
    keywords: ["xml validator", "validate xml", "xml parse error", "check xml"],
    relatedTools: ["xml-formatter", "json-validator", "html-formatter", "json-formatter"],
    isLocalOnly: true,
  },
  {
    slug: "html-formatter",
    title: "HTML Formatter",
    shortTitle: "HTML Formatter",
    description: "Pretty-print HTML text with indentation options and a compact minify mode.",
    category: "developer",
    status: published,
    seoTitle: "HTML Formatter - Format HTML Locally",
    seoDescription:
      "Format HTML locally in your browser with indentation options, minify mode, sample HTML, copy, and clear controls.",
    keywords: ["html formatter", "format html", "prettify html", "html minifier"],
    relatedTools: ["css-formatter", "javascript-formatter", "xml-formatter", "markdown-to-html"],
    isLocalOnly: true,
  },
  {
    slug: "css-formatter",
    title: "CSS Formatter",
    shortTitle: "CSS Formatter",
    description: "Format or minify CSS text with simple indentation controls and friendly failure handling.",
    category: "developer",
    status: published,
    seoTitle: "CSS Formatter - Format and Minify CSS",
    seoDescription:
      "Format CSS locally in your browser. Pretty-print stylesheets, choose indentation, minify CSS, load a sample, and copy output.",
    keywords: ["css formatter", "format css", "prettify css", "css minifier"],
    relatedTools: ["html-formatter", "javascript-formatter", "json-formatter", "text-cleaner"],
    isLocalOnly: true,
  },
  {
    slug: "javascript-formatter",
    title: "JavaScript Formatter",
    shortTitle: "JS Formatter",
    description: "Format JavaScript as text without executing it, with indentation and friendly parse warnings.",
    category: "developer",
    status: published,
    seoTitle: "JavaScript Formatter - Format JS Code Text",
    seoDescription:
      "Format JavaScript code text locally in your browser. Choose indentation, load a sample, copy output, and never execute the code.",
    keywords: ["javascript formatter", "format javascript", "prettify js", "js formatter"],
    relatedTools: ["html-formatter", "css-formatter", "json-formatter", "base64-encoder-decoder"],
    isLocalOnly: true,
  },
  {
    slug: "markdown-to-html",
    title: "Markdown to HTML",
    shortTitle: "Markdown to HTML",
    description: "Convert Markdown into sanitized HTML and preview the rendered result locally.",
    category: "markdown",
    status: published,
    seoTitle: "Markdown to HTML - Convert Markdown Locally",
    seoDescription:
      "Convert Markdown to HTML in your browser with headings, lists, links, code, blockquotes, tables, preview, sample, and copy.",
    keywords: ["markdown to html", "convert markdown", "markdown html converter", "markdown preview"],
    relatedTools: ["markdown-viewer", "markdown-editor", "html-to-markdown", "table-to-markdown"],
    isLocalOnly: true,
  },
  {
    slug: "html-to-markdown",
    title: "HTML to Markdown",
    shortTitle: "HTML to Markdown",
    description: "Convert common HTML into clean Markdown with options for links, headings, lists, and tables.",
    category: "markdown",
    status: published,
    seoTitle: "HTML to Markdown - Convert HTML Locally",
    seoDescription:
      "Convert HTML to Markdown locally in your browser. Preserve links, headings, lists, and simple tables with copy and sample controls.",
    keywords: ["html to markdown", "convert html", "markdown converter", "html markdown"],
    relatedTools: ["markdown-to-html", "markdown-editor", "markdown-viewer", "html-formatter"],
    isLocalOnly: true,
  },
  {
    slug: "table-to-markdown",
    title: "Table to Markdown",
    shortTitle: "Table Markdown",
    description: "Convert pasted CSV, TSV, or spreadsheet text into a Markdown table with alignment controls.",
    category: "markdown",
    status: published,
    seoTitle: "Table to Markdown - Convert CSV or TSV to Markdown",
    seoDescription:
      "Convert CSV, tab-separated values, or copied spreadsheet text into a Markdown table locally with header and alignment options.",
    keywords: ["table to markdown", "csv to markdown table", "tsv to markdown", "spreadsheet to markdown"],
    relatedTools: ["markdown-table-generator", "markdown-editor", "markdown-to-html", "list-cleaner"],
    isLocalOnly: true,
  },
  {
    slug: "markdown-table-generator",
    title: "Markdown Table Generator",
    shortTitle: "Table Generator",
    description: "Build a Markdown table from an editable grid with rows, columns, headers, and alignment.",
    category: "markdown",
    status: published,
    seoTitle: "Markdown Table Generator - Build Markdown Tables",
    seoDescription:
      "Generate Markdown tables locally using an editable grid. Add or remove rows and columns, set headers, align columns, and copy output.",
    keywords: ["markdown table generator", "create markdown table", "markdown table builder", "table generator"],
    relatedTools: ["table-to-markdown", "markdown-editor", "markdown-viewer", "list-cleaner"],
    isLocalOnly: true,
  },
  {
    slug: "utm-builder",
    title: "UTM Builder",
    shortTitle: "UTM Builder",
    description: "Build campaign URLs from a base link and UTM fields without storing the URL.",
    category: "links",
    status: published,
    seoTitle: "UTM Builder - Create Campaign URLs Locally",
    seoDescription:
      "Build UTM campaign URLs locally. Enter source, medium, campaign, term, and content fields, validate the base URL, and copy the final link.",
    keywords: ["utm builder", "campaign url builder", "utm generator", "tracking url builder"],
    relatedTools: ["utm-remover", "url-cleaner", "url-encoder-decoder", "slug-generator"],
    isLocalOnly: true,
  },
  {
    slug: "qr-code-generator",
    title: "QR Code Generator",
    shortTitle: "QR Generator",
    description: "Generate QR codes locally from text or URLs and download PNG or SVG output.",
    category: "links",
    status: published,
    seoTitle: "QR Code Generator - Generate QR Codes Locally",
    seoDescription:
      "Generate QR codes in your browser from text or URLs. Choose size and error correction, download PNG or SVG, and copy the source text.",
    keywords: ["qr code generator", "generate qr code", "qr png", "qr svg"],
    relatedTools: ["qr-code-reader", "url-cleaner", "utm-builder", "url-encoder-decoder"],
    isLocalOnly: true,
  },
  {
    slug: "qr-code-reader",
    title: "QR Code Reader",
    shortTitle: "QR Reader",
    description: "Upload a QR code image and decode it locally in the browser when detection is possible.",
    category: "links",
    status: published,
    seoTitle: "QR Code Reader - Decode QR Images Locally",
    seoDescription:
      "Read QR codes from uploaded images locally in your browser. Decode text, copy the result, and get a friendly message if no QR is detected.",
    keywords: ["qr code reader", "decode qr code", "qr scanner image", "read qr image"],
    relatedTools: ["qr-code-generator", "url-cleaner", "base64-encoder-decoder", "image-compressor"],
    isLocalOnly: true,
  },
  {
    slug: "image-compressor",
    title: "Image Compressor",
    shortTitle: "Image Compressor",
    description: "Compress images locally with a quality slider, optional max dimensions, preview, and size savings.",
    category: "image",
    status: published,
    seoTitle: "Image Compressor - Compress Images Locally",
    seoDescription:
      "Compress JPEG, PNG, and WebP images locally in your browser with quality and size controls, preview, savings metrics, and download.",
    keywords: ["image compressor", "compress image", "reduce image size", "browser image compression"],
    relatedTools: ["image-resizer", "image-to-webp", "remove-image-metadata", "png-to-jpg"],
    isLocalOnly: true,
  },
  {
    slug: "image-resizer",
    title: "Image Resizer",
    shortTitle: "Image Resizer",
    description: "Resize images locally by width, height, or percentage while optionally keeping aspect ratio.",
    category: "image",
    status: published,
    seoTitle: "Image Resizer - Resize Images Locally",
    seoDescription:
      "Resize images in your browser with width, height, percentage, aspect-ratio lock, preview, and local download.",
    keywords: ["image resizer", "resize image", "change image dimensions", "browser image resize"],
    relatedTools: ["image-compressor", "image-to-webp", "jpg-to-png", "remove-image-metadata"],
    isLocalOnly: true,
  },
  {
    slug: "image-to-webp",
    title: "Convert Image to WebP",
    shortTitle: "Image to WebP",
    description: "Convert common image files to WebP locally with quality control and before-and-after sizes.",
    category: "image",
    status: published,
    seoTitle: "Convert Image to WebP - Local WebP Converter",
    seoDescription:
      "Convert images to WebP locally in your browser with a quality slider, preview, file size comparison, and download.",
    keywords: ["image to webp", "convert to webp", "webp converter", "local image converter"],
    relatedTools: ["image-compressor", "image-resizer", "png-to-jpg", "jpg-to-png"],
    isLocalOnly: true,
  },
  {
    slug: "png-to-jpg",
    title: "PNG to JPG Converter",
    shortTitle: "PNG to JPG",
    description: "Convert PNG images to JPG locally with a background color for transparent pixels.",
    category: "image",
    status: published,
    seoTitle: "PNG to JPG Converter - Convert PNG Locally",
    seoDescription:
      "Convert PNG to JPG locally in your browser. Choose background color for transparency, adjust quality, preview, and download.",
    keywords: ["png to jpg", "convert png to jpg", "png jpg converter", "local image converter"],
    relatedTools: ["jpg-to-png", "image-to-webp", "image-compressor", "remove-image-metadata"],
    isLocalOnly: true,
  },
  {
    slug: "jpg-to-png",
    title: "JPG to PNG Converter",
    shortTitle: "JPG to PNG",
    description: "Convert JPG or JPEG images to PNG locally and download the converted file.",
    category: "image",
    status: published,
    seoTitle: "JPG to PNG Converter - Convert JPG Locally",
    seoDescription:
      "Convert JPG or JPEG images to PNG locally in your browser with preview, before-and-after size metrics, and download.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png", "local image converter"],
    relatedTools: ["png-to-jpg", "image-to-webp", "image-resizer", "remove-image-metadata"],
    isLocalOnly: true,
  },
  {
    slug: "remove-image-metadata",
    title: "Remove Image Metadata",
    shortTitle: "Remove Metadata",
    description: "Re-encode images through canvas to strip most common metadata before sharing.",
    category: "image",
    status: published,
    seoTitle: "Remove Image Metadata - Strip Image Metadata Locally",
    seoDescription:
      "Remove most common image metadata locally by re-encoding through the browser canvas, then preview and download the cleaned image.",
    keywords: ["remove image metadata", "strip exif", "image privacy", "metadata remover"],
    relatedTools: ["image-compressor", "image-resizer", "image-to-webp", "png-to-jpg"],
    isLocalOnly: true,
  },
  {
    slug: "online-timer",
    title: "Online Timer",
    shortTitle: "Timer",
    description: "Run a simple browser timer with presets, pause, reset, progress, sound, and saved duration.",
    category: "time",
    status: published,
    seoTitle: "Online Timer - Simple Browser Timer",
    seoDescription:
      "Use a local browser timer with presets, custom duration, start, pause, reset, progress display, completion sound, and saved preference.",
    keywords: ["online timer", "browser timer", "countdown timer", "25 minute timer"],
    relatedTools: ["stopwatch", "speaking-time-calculator", "reading-time-calculator", "word-counter"],
    isLocalOnly: true,
  },
  {
    slug: "stopwatch",
    title: "Stopwatch",
    shortTitle: "Stopwatch",
    description: "Use a browser stopwatch with start, pause, reset, laps, copyable lap summaries, and optional milliseconds.",
    category: "time",
    status: published,
    seoTitle: "Stopwatch - Simple Browser Stopwatch with Laps",
    seoDescription:
      "Run a local browser stopwatch with laps, copyable lap list, clear controls, reset, and optional millisecond display.",
    keywords: ["stopwatch", "online stopwatch", "lap timer", "browser stopwatch"],
    relatedTools: ["online-timer", "speaking-time-calculator", "reading-time-calculator", "line-counter"],
    isLocalOnly: true,
  },
];
